import assert from 'node:assert/strict';
import { BattleSim, createWildInstance } from '@pokemon-online/engine';
import { SKILL_MAP } from '@pokemon-online/config';
import { selectHealingTarget, nearbyBacklineThreat, controlRemaining, canUseControlWindow } from '../packages/engine/src/cooperation.ts';
import { decide } from '../packages/engine/src/ai.ts';
const make = (id: number, uid: string) => ({ ...createWildInstance(id, 50, { rng: () => .5 }), uid, passiveSkills: [], ability: 'keen-eye', personality: 'cool' as const });
const sim = new BattleSim({ mode: 'pvp', player: [make(113, 'heal'), make(36, 'other'), make(68, 'front')], enemy: [make(143, 'intruder'), make(6, 'remote')], seed: 51 });
const [heal, other, front, intruder, remote] = sim.state.combatants;
for (const [i, c] of sim.state.combatants.entries()) { c.position = c.pixel = { x: 5 + i, y: 7 }; c.currentHp = c.maxHp = 1000; c.stats.atk = 100; }
const move = SKILL_MAP['heal-pulse']!;
other!.currentHp = 950; front!.currentHp = 500;
assert.equal(selectHealingTarget(heal!, move, sim.state)?.patient.uid, 'front', '有效缺血优先');
other!.currentHp = 850; front!.currentHp = 850;
intruder!.currentTargetUid = 'front';
assert.equal(selectHealingTarget(heal!, move, sim.state)?.patient.uid, 'front', '同缺血时照顾承压者');
intruder!.currentTargetUid = undefined;
other!.currentHp = 900; front!.currentHp = 900;
other!.stats.atk = 200;
other!.castProgress = { skillId: 'heal-pulse', remaining: .2 }; other!.castSupportUid = 'front';
assert.equal(selectHealingTarget(heal!, move, sim.state)?.patient.uid, 'other', '不重复治疗已经足量预约的小伤口');
front!.currentHp = 300;
assert.equal(selectHealingTarget(heal!, move, sim.state)?.patient.uid, 'front', '重伤允许两人共同救援');
front!.currentHp = 850; other!.currentHp = 950;
other!.castProgress = null;
assert.equal(selectHealingTarget(heal!, move, sim.state)?.patient.uid, 'front', '打断后立即释放预约');
other!.castProgress = { skillId: 'heal-pulse', remaining: .2 }; other!.alive = false;
assert.equal(selectHealingTarget(heal!, move, sim.state)?.patient.uid, 'front', '倒下施法者不再占用治疗');
other!.alive = true; other!.castProgress = null;
// 自疗也是实际治疗预约；只有先到且可兑现的治疗才抵扣需求。
other!.currentHp = 850; front!.currentHp = 850;
front!.castProgress = { skillId: 'recover', remaining: .2 };
assert.equal(selectHealingTarget(heal!, move, sim.state)?.patient.uid, 'other', '即将完成自疗者让给其他患者');
front!.currentHp = 100; front!.stats.atk = 1000;
assert.equal(selectHealingTarget(heal!, move, sim.state)?.patient.uid, 'front', '濒危者先获得即时救援，不等后续自疗');
front!.currentHp = 850; front!.stats.atk = 100;
front!.castProgress.remaining = 1;
assert.equal(selectHealingTarget(heal!, { ...move, castTime: 1.2 }, sim.state)?.patient.uid, 'other', '慢治疗计入更早兑现的自疗');
front!.castProgress = null;
assert.equal(selectHealingTarget(heal!, { ...move, castTime: 1.2 }, sim.state)?.patient.uid, 'other', '相同缺血按稳定顺序分配');
front!.currentHp = 800;
assert.equal(selectHealingTarget(heal!, move, sim.state)?.patient.uid, 'front', '自疗中断后重新救援');
// 基础友疗即时结算，下一名治疗者直接看到真实的新血量。
heal!.currentHp = heal!.maxHp; other!.currentHp = 960; front!.currentHp = 960;
for (const c of sim.state.combatants) { c.activeSkills = [c.basicSkillId!]; c.cooldowns = {}; }
heal!.stats.atk = 100;
sim.tick(.05);
const heals = sim.state.events.filter(e => e.type === 'heal' && e.skillId === 'heal-pulse');
assert(heals.length >= 2 && new Set(heals.slice(0, 2).map(e => e.target)).size === 2, '双基础治疗实际结算分工');
// 前排反制近处突入者，保持短距离；远处敌人不触发保护追赶。
for (const c of sim.state.combatants) { c.status = null; c.statStages = { atk: 0, def: 0, spd: 0 }; c.actionReadyRemaining = 0; c.currentHp = c.maxHp; }
heal!.position = heal!.pixel = { x: 5, y: 7 };
front!.position = front!.pixel = { x: 7, y: 7 };
intruder!.position = intruder!.pixel = { x: 8, y: 7 }; intruder!.currentTargetUid = 'heal';
remote!.position = remote!.pixel = { x: 12, y: 7 };
assert.equal(nearbyBacklineThreat(front!, sim.state)?.uid, 'intruder');
front!.currentTargetUid = 'remote'; front!.targetCommitUntil = 999;
heal!.currentTargetUid = other!.currentTargetUid = 'intruder';
assert.equal(decide(front!, sim.state, () => .5)?.targetUid, 'intruder', '保护不会被目标粘性或两人分流覆盖');
assert.equal(nearbyBacklineThreat(heal!, sim.state), undefined, '后排不承担贴身保护');
intruder!.position = intruder!.pixel = { x: 16, y: 7 };
assert.equal(nearbyBacklineThreat(front!, sim.state), undefined, '不跨场追逐');
remote!.status = 'sleep'; remote!.statusTimer = .2; remote!.flinchUntil = sim.state.time + 1;
assert.equal(controlRemaining(remote!, sim.state.time), 1, '叠加控制取最长有效时间');
const burstSim = new BattleSim({ mode: 'pvp', player: [make(6, 'burst')], enemy: [make(143, 'near'), make(143, 'held')], seed: 52 });
const [burst, near, held] = burstSim.state.combatants;
burst!.position = burst!.pixel = { x: 5, y: 7 };
near!.position = near!.pixel = { x: 9, y: 6 };
held!.position = held!.pixel = { x: 9, y: 8 };
burst!.activeSkills = ['ember', 'flamethrower']; burst!.cooldowns = {};
held!.status = 'sleep'; held!.statusTimer = 2;
assert.equal(decide(burst!, burstSim.state, () => .5)?.targetUid, 'held', '同距离优先抓住已生效控制窗口');
held!.position = held!.pixel = { x: 18, y: 8 };
burst!.targetCommitUntil = 0;
assert.equal(decide(burst!, burstSim.state, () => .5)?.targetUid, 'near', '不为远处控制窗口跨场追逐');
held!.position = held!.pixel = { x: 9, y: 8 }; held!.statusTimer = .05;
burst!.targetCommitUntil = 0;
assert.equal(decide(burst!, burstSim.state, () => .5)?.targetUid, 'near', '即将消失的控制不诱发切换');
held!.statusTimer = 1;
assert(canUseControlWindow(burst!, held!, SKILL_MAP.ember!, 0));
burst!.pixel = { x: 4.5, y: 7 };
assert(!canUseControlWindow(burst!, held!, SKILL_MAP.ember!, 0), '逻辑到位但脚点未到不能利用短窗口');
burst!.pixel = burst!.position;
burst!.actionReadyRemaining = 2;
assert(!canUseControlWindow(burst!, held!, SKILL_MAP.ember!, 0), '动作未结束不假设能立即追击');
burst!.actionReadyRemaining = 0;
held!.statusTimer = .2;
assert(!canUseControlWindow(burst!, held!, SKILL_MAP['fire-blast']!, 0), '蓄力赶不上控制窗口不加权');
console.log('✓ 友疗收益与承压、双治疗真实分工、预约失效、重伤合救、就近保护与控制窗口');
