import assert from 'node:assert/strict';
import { BattleSim, createWildInstance } from '@pokemon-online/engine';
import { BattleDirector, snapshotBattle, toBattlePresentationEvent } from '@pokemon-online/presentation';
import type { BattleCombatant, BattleEvent, StatusKind } from '@pokemon-online/shared';
import { BattleOutcomeTimeline } from '../apps/web/src/game/BattleOutcomeTimeline.ts';

export function testBattleControl(): void {
  const sim = new BattleSim({ mode: 'pvp', player: [createWildInstance(94, 100)], enemy: [createWildInstance(143, 100)], seed: 904 });
  const [actor, victim] = sim.state.combatants as [BattleCombatant, BattleCombatant];
  const castProgress = { skillId: 'hyper-beam', remaining: 0.6 };
  const before = snapshotBattle(0, [{ ...victim, currentHp: 100, status: null, flinchUntil: 0, castProgress }]);
  const release: BattleEvent = { seq: 1, t: 0.1, type: 'skill', actor: actor.uid, target: victim.uid, skillId: 'hypnosis' };
  const status: BattleEvent = { ...release, seq: 2, type: 'status', vfx: { kind: 'status', status: 'sleep' },
    control: { uid: victim.uid, at: 0.104, status: 'sleep', statusTimer: 2, flinchUntil: 0 } };
  const interrupt: BattleEvent = { seq: 3, t: 0.1, type: 'info', actor: victim.uid, skillId: 'hyper-beam', message: 'arbitrary localized text',
    vfx: { kind: 'interrupt' }, control: { ...status.control!, castProgress: null } };
  const after = snapshotBattle(0.104, [{ ...victim, currentHp: 81, ...status.control, castProgress: null }]);
  const cues = new BattleDirector().direct([release, status, interrupt].map(toBattlePresentationEvent));
  const contact = Math.max(...cues.filter((cue) => cue.sequence === 2).map(({ cue }) => cue.delayMs ?? 0)) / 1000;
  assert(contact > 0, 'status skill retains its authored contact delay');
  assert.equal(toBattlePresentationEvent(interrupt).type, 'cast-interrupt', 'interruption never parses localized logs');
  assert(cues.filter((cue) => cue.sequence === 3).every(({ cue }) => cue.type === 'animation' && cue.animation === 'interrupt'), 'cancelled casts emit no release/projectile');
  const timeline = new BattleOutcomeTimeline();
  timeline.enqueue([release, status, interrupt], cues, before.combatants, () => after);
  let shown = timeline.apply(after.combatants, 0.104)[0]!;
  assert.equal(shown.status, null);
  assert.deepEqual(shown.castProgress, castProgress);
  assert.equal(shown.currentHp, 81, 'control-only records must not freeze unrelated health');
  assert.deepEqual(timeline.visibleEvents([release, status, interrupt]), [release]);
  assert.equal(timeline.advance(contact - 0.001).events.length, 0);
  assert.deepEqual(timeline.advance(0.001).events.map((event) => event.seq), [2, 3], 'interrupt follows delayed control on the same target');
  shown = timeline.apply(after.combatants, 0.104)[0]!;
  assert.equal(shown.status, 'sleep');
  assert.equal(shown.castProgress, null);
  const recovered = snapshotBattle(2.2, [{ ...victim, status: null, statusTimer: 0, castProgress: null }]);
  assert.equal(timeline.apply(recovered.combatants, 2.2)[0]!.status, null, 'expiration resumes from authoritative snapshots');
  timeline.clear();
  const nextTick = snapshotBattle(0.104, [{ ...victim, ...status.control, castProgress }]);
  timeline.enqueue([release, status], cues.filter((cue) => cue.sequence !== 3), before.combatants, () => nextTick);
  assert(timeline.apply(nextTick.combatants, 0.104)[0]!.castProgress, 'pending control cannot hide charge early');
  const landed = timeline.advance(contact);
  assert.equal(timeline.apply(nextTick.combatants, 0.104)[0]!.castProgress, null, 'visible control suppresses stale charge before the next engine tick');
  assert(!landed.events.some((event) => event.vfx?.kind === 'interrupt'), 'visual suppression does not invent an interruption');
  assert.deepEqual(nextTick.combatants[0]!.castProgress, castProgress, 'authoritative cast snapshot is not mutated');
  timeline.clear();
  const stun: BattleEvent = { ...status, vfx: { kind: 'status', status: 'paralyze' }, control: { ...status.control!, status: null, statusTimer: 0, flinchUntil: 1.1 } };
  timeline.enqueue([stun], cues.filter((cue) => cue.sequence === 2), before.combatants, () => after);
  assert.equal(timeline.apply(after.combatants, 0.104)[0]!.flinchUntil, 0);
  timeline.advance(contact);
  shown = timeline.apply(after.combatants, 0.104)[0]!;
  assert.equal(shown.status, null, 'stun visual hint cannot fabricate persistent paralysis');
  assert.equal(shown.flinchUntil, 1.1);
  timeline.clear();
  timeline.enqueue([status, interrupt], cues, before.combatants, () => after);
  timeline.clear();
  assert.equal(timeline.advance(10).events.length, 0, 'restart cancels pending control/interruption');

  const internals = sim as unknown as { inflictStatus(target: BattleCombatant, status: StatusKind, duration: number, source: BattleCombatant, skillId?: string): boolean };
  victim.ability = 'synchronize';
  victim.status = null;
  actor.status = null;
  assert(internals.inflictStatus(victim, 'sleep', 2, actor, 'hypnosis'));
  const records = sim.state.events.filter((event) => event.type === 'status');
  assert.equal(records[0]!.skillId, 'hypnosis');
  assert.equal(records[1]!.skillId, undefined, 'reflected status cannot pair with the original release');
  const recorded = JSON.stringify(records[0]!.control);
  victim.castProgress = castProgress;
  sim.tick(0.05);
  const cancelled = sim.state.events.find((event) => event.vfx?.kind === 'interrupt')!;
  assert(cancelled && cancelled.skillId === 'hyper-beam' && cancelled.control?.castProgress === null);
  assert.equal(victim.castProgress, null);
  assert(!sim.state.events.some((event) => event.type === 'skill' && event.actor === victim.uid), 'engine does not resolve interrupted skill');
  assert.equal(JSON.stringify(records[0]!.control), recorded, 'control records are immutable value copies');
  actor.status = null;
  actor.ability = 'limber';
  const count = sim.state.events.length;
  assert(!internals.inflictStatus(actor, 'paralyze', 2, victim, 'thunder-wave'));
  assert.equal(sim.state.events.length, count, 'immunity produces no fake control event');
  console.log('✓ contact-aligned control, structured interruption, expiration, reflection and immunity');
}
